[platformio]
default_envs = esp32dev
src_dir = examples/httpUpdate

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
  +<*>
  -<arduino-build/>
  -<arduino-sketch/>
  -<.pio/>
build_flags =
  -I${PROJECT_DIR}
  -ffunction-sections
  -Wl,--gc-sections
extra_scripts = pre:scripts/generate_version_header.py
monitor_speed = 115200
lib_ldf_mode = deep+
lib_extra_dirs = .